spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: iot_manager_dev
#      username: ${MONGO_USERNAME:admin}
#      password: ${MONGO_PASSWORD:password}

logging:
  level:
    com.iot: DEBUG
    org.springframework.data.mongodb: DEBUG