spring:
  profiles:
    active: dev
  application:
    name: smart-iot-manager
  data:
    mongodb:
      auto-index-creation: true

server:
  port: 8087

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret}
  expiration: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.iot: DEBUG
    org.springframework.security: INFO